# Site Information
license:          "MIT"
license-url:      "https://github.com/blairanderson/tachyonstemplates/blob/gh-pages/LICENSE"
author:           "Serverless Directory"
name:             "ServerLess Directory"
title:             "ServerLess Directory"
google_site_verification: ""
bing_site_verification: "0C81C6A5BD3BAF86F4730D8C4A9BF223"
# Site Settings
baseurl:          ""

# Build settings
exclude:          [gulp*, README*, node_modules, sass-cache, _data,Gemfile*, yarn*,LICENSE,package.json,Rakefile,github]

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
url:              https://www.serverlessconsultants.com
enforce_ssl:      http://www.serverlessconsultants.com
encoding:         UTF-8
host:             0.0.0.0
port:             9001

# Gems
gems:
  - jekyll-paginate
  - rouge

# Collections
collections:
  consultants:
    output: true
    permalink: /consultants/:title/
  frameworks:
    output: true
    permalink: /framework-overviews/:title/

# Pagination
paginate: 5
paginate_path: "/articles/page:num/"
