source 'https://rubygems.org'
ruby '2.3.1'
gem 'rake'
gem 'activesupport'
gem 'jekyll', '3.4.3'
gem 'hash-joiner'
gem 'jekyll-paginate'
gem 'jekyll-redirect-from'
gem 'rouge'
gem 'safely_block'
gem 'pry-coolline'
gem 'pry'
gem 'fast_blank'
gem 'dotenv'
