source 'https://rubygems.org'

gem 'rake'
gem 'activesupport'
gem 'jekyll'
gem 'hash-joiner'
gem 'jekyll-paginate'
gem 'jekyll-redirect-from'
gem 'rouge'
gem 'safely_block'
gem 'pry-coolline'
gem 'pry'
gem 'fast_blank'
gem 'dotenv'
